# /setup/roles/rov/tasks/main.yml
#
# ansible playbook file
#
# configures hosts for Cabrillo ROV 2023
# sub-playbook for rov configuration
#
# Copyright (C) 2022-2023 Cabrillo Robotics Club
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Cabrillo Robotics Club
# 6500 Soquel Drive Aptos, CA 95003
# cabrillorobotics@gmail.com
#
---

# allow access to i2c
- name: Add ubuntu to the dialout group
  become_user: "{{ ansible_user }}"
  become: true
  user:
    name: ubuntu
    groups: dialout
    append: yes

- name: h264 image transport extra paclages
  become: true
  apt:
    name:
    - ros-humble-v4l2-camera
    - ros-humble-image-transport-plugins
    - v4l-utils
    - libavdevice-dev
    - libavformat-dev
    - libavcodec-dev
    - libavutil-dev
    - libswscale-dev
    state: present
    cache_valid_time: 86400

- name: copy cloud init file
  become: true
  copy:
    src: user-data
    dest: /boot/user-data

- name: disable camera auto detect
  become: true
  lineinfile:
    path: /boot/firmware/config.txt
    search_string: camera_auto_detect=
    line: "#camera_auto_detect="
    state: present

- name: boot config set vram to 256
  become: true
  lineinfile:
    path: /boot/firmware/config.txt
    search_string: gpu_mem=
    line: gpu_mem=256

- name: enable xserver
  become: true
  lineinfile:
    path: /boot/firmware/config.txt
    search_string: start_x=
    line: start_x=1

- name: reboot to apply boot config
  become: true
  reboot:
