# Configuration parameters for the ros_gz_bridge node passing topics between
# ROS and Gazebo.
# See link for a list of configuration options
# https://github.com/gazebosim/ros_gz/tree/humble/ros_gz_bridge#example-5-configuring-the-bridge-via-yaml
- topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "/drive/cmd_vel"
  gz_topic_name: "/model/seahawk/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

# The OdometryPublisher plugin has an option to publish an odometry msg with
# covariance, but currently that message doesn't contain the orientation data
# https://github.com/gazebosim/gz-sim/blob/ign-gazebo6/src/systems/odometry_publisher/OdometryPublisher.cc#L462
- ros_topic_name: "/odom"
  gz_topic_name: "/model/seahawk/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "/tf"
  gz_topic_name: "/model/seahawk/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: GZ_TO_ROS
