#
# ansible_playbook.yml
#
---

- name: Host install & configure
  become: yes
  become_user: root
  hosts: all
  tasks:

  - name: Ensure systemd and udev upgrades happen first
    ansible.builtin.apt:
      name:
        - systemd
      state: latest
      cache_valid_time: 86400 # consider cache up-to-date if its < 1 day old
      # this also sets update_cache: true implicitly, so that can be left out

  - name: Install ROS2 GPG keys
    ansible.builtin.apt_key: # TODO: retire depracated tool apt-key
      url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
 
  - name: Add ROS2 Humble apt repo
    ansible.builtin.apt_repository:
      repo: deb http://packages.ros.org/ros2/ubuntu jammy main

  - name: Install components from apt
    ansible.builtin.apt:
      name:
      - python3-pip
      - curl
      - gnupg
      - lsb-release
      - ros-humble-ros-desktop # TODO: Not everything by default
        # We should look at what is actually needed on ALL hosts, and only grab that

  - name: Remove unattended-upgrades
    ansible.builtin.apt:
      state: absent
      name:
      - unattended-upgrades

  - name: Install components from pip
    ansible.builtin.pip:
      state: latest
      name:
      - ansible
      - adafruit-circuitpython-servokit
      - adafruit-circuitpython-motorkit
     
