

- name: Install development box tools.
  hosts: all 
  become: yes
  roles:
    - common 
    - ros
  tasks:
  - name: Install vscode
    community.general.snap:
      name: code
      classic: true
  - name: Install extra ROS packages.
    apt:
      name:
        - rviz
        - ros-humble-desktop-full
        - python3-colcon-common-extensions
        - qemu-user-static
        - python3-venv 
        - python3-rosdep2
        - docker.io 
      state: present
  - name: Add student to the docker group
    user:
      name: student
      groups: docker
      append: yes
