

- name: Install development box tools.
  hosts: all 
  become: yes
  roles:
    - ros
    - common
  tasks:
  - name: Install ROS2 desktop packages.
    apt:
      name:
        - rviz
        - ros-humble-desktop-full
        - python3-colcon-common-extensions
        - python3-venv 
        - python3-rosdep2
        - gcc-arm-none-eabi 
        - libnewlib-arm-none-eabi 
        - cmake 
        - doxygen 
      state: present
