# ansible_inventory.yaml
# 
# ansible inventory for setting up hosts in the cabrill rov for the mate rov 2023 competition
#
# Copyright (C) 2022-2023 Cabrillo Robotics Club
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Cabrillo Robotics Club
# 6500 Soquel Drive Aptos, CA 95003
# cabrillorobotics@gmail.com
#
rov:
  hosts:
    SeaHawk-1:
      ansible_user: ubuntu
      ansible_ssh_pass: Cabri11o
      ansible_become_pass: Cabri11o
      ansible_host: 192.168.254.101
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    SeaHawk-2:
      ansible_user: ubuntu
      ansible_ssh_pass: Cabri11o
      ansible_become_pass: Cabri11o
      ansible_host: 192.168.254.102
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

deck:
  hosts:
    Deck_Placeholder_Name:
      # TODO: The whole deck computer. Oops.


