# hosts.yaml
#
# ansible inventory file
# 
# configures hosts for Cabrillo ROV 2023
# main inventory file
#
# Copyright (C) 2022-2023 Cabrillo Robotics Club
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Cabrillo Robotics Club
# 6500 Soquel Drive Aptos, CA 95003
# cabrillorobotics@gmail.com
#

---
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# Group the hosts according to their jobs. ROV, Deck, Devkits, and any more   #
# you can think of. These are the main definitions. The authoritative source  #
# of truth for our inventory.                                                 #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
#
# A host must have the following variables:
#  ansible_user
#  ansible_host
#  ansible_become_pass

rov:
  hosts:
    SeaHawk-ROV:
      ansible_host: seahawk-rov.local
      ansible_user: ubuntu
      ansible_ssh_pass: Cabri11o
      ansible_become_pass: Cabri11o
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    SeaHawk-ROV-SPARE:
      ansible_host: seahawk-rov-spare.local
      ansible_user: ubuntu
      ansible_ssh_pass: Cabri11o
      ansible_become_pass: Cabri11o
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    SeaHawk-ROV-Ciaran:
      #ansible_host: seahawk-rov-ciaran.local
      ansible_host: 192.168.22.41
      ansible_user: ubuntu
      ansible_ssh_pass: Cabri11o
      ansible_become_pass: Cabri11o
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

deck:
  hosts:
    SeaHawk-DECK:
      ansible_host: seahawk-deck.local
      ansible_user: ubuntu
      ansible_ssh_pass: Cabri11o
      ansible_become_pass: Cabri11o
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    SeaHawk-DECK-Ciaran:
      ansible_host: seahawk-deck-ciaran.local
      ansible_user: ubuntu
      ansible_ssh_pass: Cabri11o
      ansible_become_pass: Cabri11o
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'


devkits:
  hosts:
    # Empty, for the main inventory file.
    # If we get a dedicated development machine, we can add it here.
    # NEVER use the local connection from this main inventory.
    # For that, use the hosts_devkit.yaml file. It's already set up for self-operation
