# playbook-deploy.yaml
#
# ansible playbook file
#
# deploys hosts for Cabrillo ROV 2023
#
# assumes starting with blank ubuntu-server 22.04 LTS
#
#
# Copyright (C) 2022-2023 Cabrillo Robotics Club
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Cabrillo Robotics Club
# 6500 Soquel Drive Aptos, CA 95003
# cabrillorobotics@gmail.com
#
---

- name: provision common
  hosts: all
  become: true
  become_user: root
  roles:
    - common

- name: provision ros
  hosts: ros_hosts
  become: true
  become_user: root
  roles:
    - ros

- name: provision rov
  hosts: rov
  become: true
  become_user: "{{ ansible_user }}"
  roles:
    - rov

- name: provision deck
  hosts: deck
  roles:
    - deck

- name: software setup
  hosts: rov, deck
  tasks:

  - name: git pull
    become: false
    git:
      dest: /home/ubuntu/cabrillo_rov_2023
      repo: https://github.com/CabrilloRoboticsClub/cabrillo_rov_2023.git
      track_submodules: true

  - name: rosdep init
    become: true
    ignore_errors: true
    shell:
      chdir: /home/ubuntu/cabrillo_rov_2023
      cmd: "rosdep init"
