#
# Playbook to setup a clean ROV image 
# 
# This assumes a fresh Ubuntu install.
# 
- name: Configure the RPi to be an ROV
  hosts: all 
  become: yes
  tasks:
    # This will fail if you try it on a desktop. Good.
    - name: Set kernel command line parameters to remove ttyS0
      ansible.builtin.copy:
        content: 'dwc_otg.lpm_enable=0 console=tty1 root=LABEL=writable rootfstype=ext4 rootwait fixrtc quiet splash'
        dest: /boot/firmware/cmdline.txt

    - name: disable camera auto detect
      become: true
      lineinfile:
        path: /boot/firmware/config.txt
        regexp: camera_auto_detect=
        line: "#camera_auto_detect="
        state: present

    - name: Set gpu_mem
      become: true
      lineinfile:
        path: /boot/firmware/config.txt
        regexp: gpu_mem=
        line: gpu_mem=256

    - name: Set i2c baud rate
      become: true
      lineinfile:
        path: /boot/firmware/config.txt
        regexp: dtparam=i2c_arm_baudrate=
        line: 'dtparam=i2c_arm_baudrate=400000'

    - name: Set start_x  
      become: true
      lineinfile:
        path: /boot/firmware/config.txt
        regexp: start_x=
        line: start_x=1

    # Access to i2c
    - name: Add ubuntu to the dialout group
      become: true
      user:
        name: ubuntu
        groups: dialout
        append: yes

    - name: Disable eee using /etc/rc.local
      ansible.builtin.copy:
        content: |
          #! /bin/bash 
          ethtool --set-eee eth0 eee off
        dest: /etc/rc.local
        owner: root
        group: root
        mode: '0755'

    - name: Make sudo passwordless for members of sudo
      lineinfile:
        path: /etc/sudoers
        regexp: "^%sudo"
        line: "%sudo   ALL=(ALL:ALL) NOPASSWD: ALL"

    - name: Improve performance of vscode 
      ansible.posix.sysctl:
        name: fs.inotify.max_user_watches
        value: '524288'
        state: present


- name: Install ROV tools
  hosts: all 
  become: yes
  roles:
    - ros
    - common
  tasks:
  - name: Install ROV packages.
    apt:
      name:
        - automake 
        - autoconf 
        - build-essential 
        - texinfo 
        - libtool 
        - libftdi-dev 
        - libusb-1.0-0-dev
        - gdb-multiarch
        - avahi-daemon
      state: present

- name: Install OpenOCD from source
  hosts: all
  become: yes
  tasks:
  - ansible.builtin.shell: 
      chdir: /tmp
      creates: /usr/local/bin/openocd
      cmd: |
        set -e
        git clone https://github.com/raspberrypi/openocd.git --branch rp2040-v0.12.0 --depth=1
        cd openocd
        ./bootstrap  
        ./configure --enable-sysfsgpio --enable-bcm2835gpio
        make -j4  
        make install
        cd .. 
        rm -rf openocd

- name: Add user accounts
  hosts: all 
  become: yes
  vars:
    users:
      - { name: 'mmatera', comment: 'Mike Matera', ghuser: 'mike-matera' }
      - { name: 'liam', comment: 'Liam Gilligan', ghuser: 'liamgilligan' }
      - { name: 'taschnell', comment: 'Teo Schnell', ghuser: 'taschnell' }
      - { name: 'steph', comment: "Stephanie L'Heureux", ghuser: 'steph1111' }
      - { name: 'cjbf', comment: 'CJ Bridgman-Ford', ghuser: 'cjikaika' }
      - { name: 'michaelatobias', comment: 'Michael Tobias', ghuser: 'michaelatobias' }
      - { name: 'katew', comment: 'Kate Wolsfeld', ghuser: 'Katewolsfeld10' }
      - { name: 'akcarney', comment: 'Ava Carney', ghuser: 'akcarney' }
      - { name: 'orion', comment: 'Orion Ellefson', ghuser: 'OrionOth' }
      - { name: 'massimo', comment: 'Massimo Ginella', ghuser: 'tinymassi' }
      - { name: 'wwb', comment: 'Weston Brown', ghuser: 'onwest' }
      - { name: 'katerosep', comment: 'Kate Rosenbloom Pohl', ghuser: 'katerosep' }
      - { name: 'theo', comment: 'Theo Paris', ghuser: 'theoparis'}
      - { name: 'whitlockmcorbett', comment: 'Corbett Whitlock', ghuser: 'whitlockmcorbett'}
      - { name: 'daniel', comment: 'Daniel Bledsoe', ghuser: 'epic-coding-23' }
  tasks:
    - name: Add user
      ansible.builtin.user:
        name: "{{ item.name }}"
        comment: "{{ item.comment }}"
        shell: /usr/bin/bash
        groups:  adm,dialout,cdrom,floppy,sudo,audio,dip,video,plugdev,netdev,lxd,docker
        state: present
      loop: "{{ users }}"
    - name: Import keys from GitHub
      ansible.posix.authorized_key:
        user: "{{ item.name }}"
        key: "https://github.com/{{ item.ghuser }}.keys"
        state: present
      loop: "{{ users }}"
