#
# Playbook to setup a clean ROV image 
# 
# This assumes a fresh Ubuntu install.
# 
- name: Install development box tools.
  hosts: all 
  become: yes
  tasks:
    # This will fail if you try it on a desktop. Good.
    - name: disable camera auto detect
      become: true
      lineinfile:
        path: /boot/firmware/config.txt
        regexp: camera_auto_detect=
        line: "#camera_auto_detect="
        state: present

    - name: Set gpu_mem
      become: true
      lineinfile:
        path: /boot/firmware/config.txt
        regexp: gpu_mem=
        line: gpu_mem=256

    - name: Set i2c baud rate
      become: true
      lineinfile:
        path: /boot/firmware/config.txt
        regexp: dtparam=i2c_arm_baudrate=
        line: 'dtparam=i2c_arm_baudrate=400000'

    - name: Set start_x  
      become: true
      lineinfile:
        path: /boot/firmware/config.txt
        regexp: start_x=
        line: start_x=1

    # Access to i2c
    - name: Add ubuntu to the dialout group
      become_user: "{{ ansible_user }}"
      become: true
      user:
        name: ubuntu
        groups: dialout
        append: yes

- name: Install development box tools.
  hosts: all 
  become: yes
  roles:
    - ros
    - common
